baseURL = 'https://gnistor.se/'
languageCode = 'sv-SE'
defaultContentLanguage = 'sv'
defaultContentLang = 'sv'
title = 'Gnistor'
buildFuture = true
timeZone = 'Europe/Stockholm'
[taxonomies]
	location = 'locations'
	form = 'forms'
	topic = 'topics'
[sitemap]
	changefreq = 'always'
	filename = 'sitemap.xml'
	priority = 0.5
[outputFormats]
[outputFormats.feed]
	mediatype = "application/rss+xml"
	path = "/feed"
[outputFormats.json]
	mediatype = "application/json"
	baseName = "feed"
	isPlainText = true
[outputFormats.calendar]
	  baseName = "calendar"
	  # Avoid unencrypted webcal scheme
	  protocol = "https://"
	  permalinkable = true
[outputs]
	home = [ "HTML", "feed", "json", "calendar" ]
	page = [ "HTML", "calendar" ]
[params]
[params.author]
	name = 'Gnistor'
	email = 'hej@gnistor.se'
[params.podcast]
	description = 'Gnistor är en mikro-podd där vi försöker ta reda på vad som händer bland Sveriges sociala rörelser. I varje avsnitt ställer vi några snabba frågor till en grupp eller en person som har något spännande som på gång.'
	tagline = 'Gnistor, en podd som rör sig.'
	download_url = 'https://media.gnistor.se/'
	cdn_url = 'https://media.gnistor.se/'